version: "3.7"
services:
  webserver:
  image: nginx:latest
  deploy:
    replicas: 3
    placement:
      constraints:
        - "node.hostname!=manager2"

  dbserver:
    image: mysql:8.0.20
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress-admin
      MYSQL_PASSWORD: wordpress
    volumes:
      - type: volume
        source: /db-data
        target: /var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==manager2"

volumes:
  db-data:
